# Generated by Django 4.2.7 on 2025-08-28 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['-is_featured', '-rating', 'name']},
        ),
        migrations.AddField(
            model_name='place',
            name='average_temperature',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='best_time_to_visit',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('heritage', 'Heritage'), ('beaches', 'Beaches'), ('temples', 'Temples'), ('adventure', 'Adventure'), ('hills', 'Hills'), ('wildlife', 'Wildlife'), ('cultural', 'Cultural')], default='cultural', max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='place',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='opening_hours',
            field=models.CharField(default='6:00 AM - 6:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='place',
            name='state',
            field=models.CharField(choices=[('ap', 'Andhra Pradesh'), ('telangana', 'Telangana')], default='ap', max_length=20),
        ),
        migrations.AddField(
            model_name='place',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='place',
            name='season',
            field=models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], default='summer', max_length=20),
        ),
    ]
