# Generated by Django 4.2.7 on 2025-08-28 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('time_slot', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening'), ('night', 'Night')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('duration_hours', models.DecimalField(decimal_places=1, default=2.0, max_digits=3)),
                ('includes_food', models.BooleanField(default=False)),
                ('food_description', models.TextField(blank=True, null=True)),
                ('day_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='packages.package')),
            ],
            options={
                'ordering': ['day_number', 'time_slot'],
                'unique_together': {('package', 'day_number', 'time_slot')},
            },
        ),
    ]
