# Generated by Django 4.2.7 on 2025-09-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text='Event image', null=True, upload_to='events/'),
        ),
    ]
