services:
  # Web Service
  - type: web
    name: prayanam-admin
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn travel_platform.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: prayanam-admin.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: prayanam-db
          property: connectionString
      - key: STATIC_URL
        value: /static/
      - key: MEDIA_URL
        value: /media/
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: True
      - key: SITE_NAME
        value: Prayanam Admin
      - key: SITE_DOMAIN
        value: https://prayanam-org.onrender.com

  # PostgreSQL Database
  - type: pserv
    name: prayanam-db
    plan: free
    env: postgresql
    version: 16
