services:
  # Web Service
  - type: web
    name: prayanam-app
    env: python
    plan: free
    runtime: python-3.11
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && python setup_admin_data.py && python create_telugu_states_data.py && python add_place_images.py
    startCommand: gunicorn travel_platform.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: prayanam-app.onrender.com
      - key: USE_SQLITE
        value: True
      - key: STATIC_URL
        value: /static/
      - key: MEDIA_URL
        value: /media/
      - key: EMAIL_HOST
        value: smtp.gmail.com
      - key: EMAIL_PORT
        value: 587
      - key: EMAIL_USE_TLS
        value: True
      - key: EMAIL_HOST_USER
        value: team.prayanam@gmail.com
      - key: EMAIL_HOST_PASSWORD
        value: wvgvepdulmeuspug
      - key: SITE_NAME
        value: Prayanam Admin
      - key: SITE_DOMAIN
        value: https://prayanam-app.onrender.com
