# Generated by Django 4.2.7 on 2025-08-28 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language_preference',
            field=models.CharField(choices=[('en', 'English'), ('te', 'తెలుగు'), ('hi', 'हिन्दी')], default='en', max_length=2),
        ),
    ]
