# Generated by Django 4.2.7 on 2025-08-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='food_preference',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('mixed', 'Mixed (Veg & Non-Veg)'), ('none', 'No Food Required')], default='mixed', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='from_date',
            field=models.DateField(blank=True, help_text='Start date of the trip', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='to_date',
            field=models.DateField(blank=True, help_text='End date of the trip', null=True),
        ),
        migrations.AddField(
            model_name='bookingmember',
            name='food_preference',
            field=models.CharField(choices=[('veg', 'Vegetarian'), ('non_veg', 'Non-Vegetarian'), ('mixed', 'Mixed (Veg & Non-Veg)'), ('none', 'No Food Required')], default='mixed', max_length=20),
        ),
    ]
